FROM ubuntu:14.04

RUN echo "Acquire::http::Proxy \"http://210.61.148.195:8080\";\n" > /etc/apt/apt.conf.d/01proxy && apt-get update && apt-get install --fix-missing -y --no-install-recommends \
    python-pip \
    && pip install -U pip setuptools pandas
